source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STLocationRequest_Example' do
  pod "STLocationRequest", :path => "../"
end

target 'STLocationRequest_Tests' do
  inherit! :search_paths
end
