source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STLocationRequest_Example', :exclusive => true do
  pod "STLocationRequest", :path => "../"
end

target 'STLocationRequest_Tests', :exclusive => true do
  pod "STLocationRequest", :path => "../"

  
end
