fastlane_version "2.62.1"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan(
      project: "STLocationRequest.xcodeproj",
      scheme: "STLocationRequest"
    )
  end
  
end
